FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Equipment Service

Equipment API allows users to assign and un-assign devices to patients.  It is also 
possible to create an assignment without a serial number.  Assignments without serial
numbers can be edited to include the serial number.

## Assignments Collection [/equipmentassignment/patient/{patientGUID}]

### Patient Assignments [GET]

Returns a list of device assignments for a given patient.

+ Parameters
    + patientGUID: 1 - A unique patient ID
    
+ Response 200 (application/json)

        [
          {
            "serialNumber": "P123456789012",
            "patientUUID": "4f1fe595-419a-a669-a2e8-22e271da4f80",
            "equipmentType": "DeviceOne",
            "assignmentDate": "2015-04-19T04:00:00.000Z",
            "userName": null
          },
          {
            "serialNumber": "P210987654321",
            "patientUUID": "4f1fe595-419a-a669-a2e8-22e271da4f80",
            "equipmentType": "DeviceTwo",
            "assignmentDate": "2015-04-19T04:00:00.000Z",
            "userName": null
          }
        ]


### Save Assignment [POST]

For creating an equipment assignment. It takes a JSON
object containing a device serial number and assignment date.

+ Parameters
    + patientGUID: 1 - A unique patient ID
  
+ Request (application/json)

        {
            "serialNumber": "P123456789012",
            "equipmentType": "Device",
            "assignmentDate": "2015-04-19T04:00:00.000Z",
            "userName": null
        }

+ Response 201 (application/json)

    + Headers

    + Body

            {
                "validationErrors": null
            }

## Assignments Collection [/equipmentassignment/patient/{patientGUID}/equipment/{serialNumber}]

### Delete Equipment [DELETE]

+ Parameters
    + patientGUID: 1 - A unique patient ID
  
+ Response 204 (application/json)

    + Headers

    + Body
